version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fleetdb
      MYSQL_USER: fleetuser
      MYSQL_PASSWORD: fleetpassword
    ports:
      - "3306:3306"
    networks:
      - fleetnetwork

  app:
    build: .
    container_name: fleetmanagement-container
    restart: always
    depends_on:
      - mysql  # ✅ Ensures MySQL starts first
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=fleetdb;User=fleetuser;Password=fleetpassword;"
    ports:
      - "5222:5222"
    networks:
      - fleetnetwork

networks:
  fleetnetwork:
